### ISSUE TITLE
Change the design of the login buttons to this

### ISSUE THREAD

**Issue by JayjeetAtGithub** [romitkarmakar/digitalfortress_frontend#4]
<img width="162" alt="Screenshot 2019-10-07 at 11 58 22 AM" src="https://user-images.githubusercontent.com/33978990/66289265-cf10db80-e8f9-11e9-97c1-96f14f5db8a7.png">
<img width="162" alt="Screenshot 2019-10-07 at 11 58 07 AM" src="https://user-images.githubusercontent.com/33978990/66289278-d506bc80-e8f9-11e9-9914-b4372f43b8dc.png">

**Comment by romitkarmakar** [comment]
@magarwal775 is working on it !!!!!

**Comment by JayjeetAtGithub** [comment]
@romitkarmakar Cool

**Comment by romitkarmakar** [comment]
@Anushka7479 resolved this issue.

**Comment by romitkarmakar** [comment]
Closing issue due to PR #6 .
